services:
  gateway:
    build: ./backend
    restart: unless-stopped
    privileged: true
    ports:
      - "8000:8000"
    environment:
      - NAS_HOST=${NAS_HOST}
      - NAS_SHARE=${NAS_SHARE}
      - NAS_USER=${NAS_USER}
      - NAS_PASS=${NAS_PASS}
      - NAS_SERVER_NAME=${NAS_SERVER_NAME}
      - CACHE_DIR=/cache
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - "./cache:/cache"
      - "./backend:/app"
      - "/app/node_modules"
      - nas_share:/nas:ro
      - "D:/Videos:/media:ro"

volumes:
  nas_share:
    driver: local
    driver_opts:
      type: cifs
      device: "//${NAS_HOST}/${NAS_SHARE}"
      o: "username=${NAS_USER},password=${NAS_PASS},uid=1000,gid=1000,iocharset=utf8,noperm"
